const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VaZd2Vp1noyym7SMa20T";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VaZd2Vp1noyym7SMa20T" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d9fd9b0046cc85fcf7063.jpg" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ 


𓆰卄𝙪z𝙖͢͠ɪғʌꦿ⟵кɪɴɢ⟶𓆪" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923405510035";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "" // "https://i.imgur.com/YyGZ1Vb.jpeg" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "recording" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_03_27_06_23_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOTYsXG4gICAgICAgIDE4NyxcbiAgICAgICAgNTMsXG4gICAgICAgIDMzLFxuICAgICAgICA5OSxcbiAgICAgICAgMjI4LFxuICAgICAgICAyMDYsXG4gICAgICAgIDcwLFxuICAgICAgICAxODAsXG4gICAgICAgIDU3LFxuICAgICAgICA4MCxcbiAgICAgICAgMTk2LFxuICAgICAgICA1MSxcbiAgICAgICAgODksXG4gICAgICAgIDI0MSxcbiAgICAgICAgMTcxLFxuICAgICAgICAxMDQsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTY2LFxuICAgICAgICAyNTQsXG4gICAgICAgIDI4LFxuICAgICAgICAxODIsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTQ4LFxuICAgICAgICAxNzgsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTIzLFxuICAgICAgICAxMzAsXG4gICAgICAgIDIxNixcbiAgICAgICAgOTYsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMTEzXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0MSxcbiAgICAgICAgMTU4LFxuICAgICAgICA3MCxcbiAgICAgICAgMjEwLFxuICAgICAgICAwLFxuICAgICAgICA4NCxcbiAgICAgICAgMjMzLFxuICAgICAgICAyMTQsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMTYzLFxuICAgICAgICA4NixcbiAgICAgICAgMTUyLFxuICAgICAgICA2MixcbiAgICAgICAgMjMxLFxuICAgICAgICAxNTMsXG4gICAgICAgIDIsXG4gICAgICAgIDc5LFxuICAgICAgICA0NyxcbiAgICAgICAgMzgsXG4gICAgICAgIDE2LFxuICAgICAgICA2LFxuICAgICAgICAxOTYsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjE4LFxuICAgICAgICAyMTMsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTk4LFxuICAgICAgICA1MyxcbiAgICAgICAgNzAsXG4gICAgICAgIDUzLFxuICAgICAgICAxODUsXG4gICAgICAgIDYzXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0OCxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMTksXG4gICAgICAgIDk1LFxuICAgICAgICAyMjQsXG4gICAgICAgIDIzMCxcbiAgICAgICAgOTMsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTAzLFxuICAgICAgICAxMTUsXG4gICAgICAgIDIzNCxcbiAgICAgICAgNzAsXG4gICAgICAgIDE4NSxcbiAgICAgICAgNzQsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTI5LFxuICAgICAgICAyMzIsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjM4LFxuICAgICAgICAyNTMsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMjIzLFxuICAgICAgICA5OSxcbiAgICAgICAgOTgsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTU2LFxuICAgICAgICAyMTQsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMjUyLFxuICAgICAgICAxODMsXG4gICAgICAgIDI1MCxcbiAgICAgICAgODNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMSxcbiAgICAgICAgMjU0LFxuICAgICAgICA0NixcbiAgICAgICAgMTQ1LFxuICAgICAgICAxODgsXG4gICAgICAgIDgxLFxuICAgICAgICAzOCxcbiAgICAgICAgNDUsXG4gICAgICAgIDU2LFxuICAgICAgICAyNDAsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTE1LFxuICAgICAgICAxMjUsXG4gICAgICAgIDQxLFxuICAgICAgICA4LFxuICAgICAgICAyMTYsXG4gICAgICAgIDIwLFxuICAgICAgICAyMjcsXG4gICAgICAgIDkxLFxuICAgICAgICA5OSxcbiAgICAgICAgMjE1LFxuICAgICAgICAyNixcbiAgICAgICAgMTQ5LFxuICAgICAgICAxOTQsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTA1LFxuICAgICAgICAxMzMsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMSxcbiAgICAgICAgMjI3LFxuICAgICAgICA1NyxcbiAgICAgICAgMTEzXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA1NixcbiAgICAgICAgODAsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTUsXG4gICAgICAgIDExLFxuICAgICAgICAyNTAsXG4gICAgICAgIDE0OSxcbiAgICAgICAgODgsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTczLFxuICAgICAgICAyMTYsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjI3LFxuICAgICAgICAzMixcbiAgICAgICAgMjQ4LFxuICAgICAgICAxMjQsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMjA2LFxuICAgICAgICAxNzUsXG4gICAgICAgIDg0LFxuICAgICAgICAxMTksXG4gICAgICAgIDY2LFxuICAgICAgICAxNyxcbiAgICAgICAgMjEzLFxuICAgICAgICAxODUsXG4gICAgICAgIDc2LFxuICAgICAgICAxMjUsXG4gICAgICAgIDM4LFxuICAgICAgICAxNzIsXG4gICAgICAgIDQ4LFxuICAgICAgICAyNTEsXG4gICAgICAgIDExOFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxODMsXG4gICAgICAgIDcyLFxuICAgICAgICA0OCxcbiAgICAgICAgMTQsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTIzLFxuICAgICAgICAxNTksXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTE4LFxuICAgICAgICAyNDksXG4gICAgICAgIDY1LFxuICAgICAgICAxOSxcbiAgICAgICAgMTk2LFxuICAgICAgICA1NixcbiAgICAgICAgNjgsXG4gICAgICAgIDIzMCxcbiAgICAgICAgOTAsXG4gICAgICAgIDQ3LFxuICAgICAgICA3NCxcbiAgICAgICAgMTg5LFxuICAgICAgICAxOTAsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMzcsXG4gICAgICAgIDM1LFxuICAgICAgICA3MixcbiAgICAgICAgMTg5LFxuICAgICAgICAyMCxcbiAgICAgICAgNDUsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMjAxLFxuICAgICAgICA1MixcbiAgICAgICAgNzNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICA4MCxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDEzOCxcbiAgICAgICAgICA1MixcbiAgICAgICAgICA2NSxcbiAgICAgICAgICA0MixcbiAgICAgICAgICA1NixcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDUsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgMjEyLFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDIyMCxcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgMTAzLFxuICAgICAgICAgIDExNlxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA4MixcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMTIxLFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICA3NixcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgMTk0LFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgNzAsXG4gICAgICAgICAgMjM0LFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDEzLFxuICAgICAgICAgIDgsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDcsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDEyNSxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICA1OSxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgNzdcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0MyxcbiAgICAgICAgMTYyLFxuICAgICAgICAxMzUsXG4gICAgICAgIDg1LFxuICAgICAgICAxMzAsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTE3LFxuICAgICAgICAxNzQsXG4gICAgICAgIDcwLFxuICAgICAgICAxMDQsXG4gICAgICAgIDIwLFxuICAgICAgICAxNSxcbiAgICAgICAgNDMsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjMxLFxuICAgICAgICA4MyxcbiAgICAgICAgOTksXG4gICAgICAgIDEyMCxcbiAgICAgICAgNTIsXG4gICAgICAgIDEzNCxcbiAgICAgICAgNjksXG4gICAgICAgIDE5LFxuICAgICAgICAxNTksXG4gICAgICAgIDMsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTAxLFxuICAgICAgICAyMjEsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTk2LFxuICAgICAgICA1NSxcbiAgICAgICAgMjIzLFxuICAgICAgICAxNzQsXG4gICAgICAgIDE3NixcbiAgICAgICAgODAsXG4gICAgICAgIDg3LFxuICAgICAgICAxODcsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTQyLFxuICAgICAgICA1MixcbiAgICAgICAgMTAwLFxuICAgICAgICAyNyxcbiAgICAgICAgNDMsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMjQ3LFxuICAgICAgICAwLFxuICAgICAgICAyOSxcbiAgICAgICAgNDUsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjAwLFxuICAgICAgICAxNSxcbiAgICAgICAgMjE5LFxuICAgICAgICAyMTAsXG4gICAgICAgIDksXG4gICAgICAgIDYsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTQ4LFxuICAgICAgICAyMjAsXG4gICAgICAgIDY2LFxuICAgICAgICA1OCxcbiAgICAgICAgMTcsXG4gICAgICAgIDE4MCxcbiAgICAgICAgMjA5LFxuICAgICAgICAyMzgsXG4gICAgICAgIDE0MVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMzYsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiRE5uejJXM3hna21TdXl3UkkzYWlNaEdQU2cwTWlRVEpHUkhVK0N0R0ViYz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW10sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiaWUtLXZFSXRRTVd2Y29ueTN5NHY3d1wiLFxuICBcInBob25lSWRcIjogXCJhMmU2MGY2MS0xMTNlLTQxNjQtYmRiZS1hYjFlMWI2YjU1MTBcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgNDcsXG4gICAgICAxNjEsXG4gICAgICAxNjAsXG4gICAgICA0MyxcbiAgICAgIDU0LFxuICAgICAgMTI2LFxuICAgICAgMjM0LFxuICAgICAgOTksXG4gICAgICAyMTcsXG4gICAgICA1MCxcbiAgICAgIDIwNSxcbiAgICAgIDU2LFxuICAgICAgMTIxLFxuICAgICAgNTUsXG4gICAgICAzMixcbiAgICAgIDIwNixcbiAgICAgIDEwNSxcbiAgICAgIDI1MSxcbiAgICAgIDIzNCxcbiAgICAgIDIwXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMjgsXG4gICAgICAxNSxcbiAgICAgIDEwMSxcbiAgICAgIDE5NyxcbiAgICAgIDExNCxcbiAgICAgIDg5LFxuICAgICAgMTg0LFxuICAgICAgMjE5LFxuICAgICAgNDgsXG4gICAgICAxNDUsXG4gICAgICAyMyxcbiAgICAgIDczLFxuICAgICAgMTkzLFxuICAgICAgNzYsXG4gICAgICAxODAsXG4gICAgICAyMjUsXG4gICAgICAzLFxuICAgICAgMTQzLFxuICAgICAgMTgxLFxuICAgICAgMjA2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDUDZHdnR3SEVJZXMzck1HR0FRZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJjc1pSUmJjVVB2YWY3RDNUQmdTSndJeUhGcGhua29NdzJmRXh1VTQydndZPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIkVZMWtwSWVqZ1hBR0l5ci9jUUxQMmJ5ZlZCSStIRklZRWFqWDFjdFRhMG9id3lYdHNSVjZDTEpNcjhqRGJwcUx6dUVMZkFXQkY4TWtBWlM3Q1F6b0RRPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIlV5dWV5QTlRN2MzZ2NrdVhQaFpURnNJTjlDNlc3Uy80eGN2Zm5yRDgwWGRidER3SFI3Kyt4UTZJR0dGVWNyemRvN0N5QjkyeHQrdmZ5cERlNFowdmh3PT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTIzNDA1NTEwMDM1OjQwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIzMDQwODQzNTU3NjkzNTo0MEBsaWRcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjkyMzQwNTUxMDAzNTo0MEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgODEsXG4gICAgICAgICAgNjksXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDIwLFxuICAgICAgICAgIDYyLFxuICAgICAgICAgIDI0NixcbiAgICAgICAgICAxNTksXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMTM3LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMTQ2LFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICA0OCxcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDE4NSxcbiAgICAgICAgICA3OCxcbiAgICAgICAgICA1NCxcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgNlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzE5MTEzMjI2LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFDVUFBSmlTXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKaU0uanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJLMGgyZXdyZXVieWE4ZWRFQmRWdGJhTVJaczJ4ZFZqcktwT0lGTGRsaTU4PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjIwNzMwMDI4NzgsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcxODM3ODM4NTM1MlwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUppTy5qc29uIjogIntcImtleURhdGFcIjpcIkpqdU9wcXFnSC93RXhCaW9rMFpBbTV5Zkc2UlZLYjljL1hGdXV4aFFJWms9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjA3MzAwMjg3OCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE4OTQ5MzIwMjY3XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSmlQLmpzb24iOiAie1wia2V5RGF0YVwiOlwibUtlbmo1bE5IRFozRElTZHZyZVNWQjRlMU1aQUNROENLeVlUV2FPN1Btbz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMDczMDAyODc4LFwiY3VycmVudEluZGV4XCI6MixcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTg5NDk1MTQyNDFcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKaVIuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCIxVmx1L0xOTUFoQUdwMGNpU1RGTHVYcXJzcllDbTVDeUVncWhxK1RsdXhnPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjIwNzMwMDI4NzgsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsM119LFwidGltZXN0YW1wXCI6XCIxNzE4OTQ5OTMzNTk5XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSmlULmpzb24iOiAie1wia2V5RGF0YVwiOlwieThRWkJsRGJIVDhWaUhpNVloVllLbVQwNnFrVkpmYUl1Qi91NTJLR01Lcz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMDczMDAyODc4LFwiY3VycmVudEluZGV4XCI6MyxcImRldmljZUluZGV4ZXNcIjpbMCwxLDNdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUppVS5qc29uIjogIntcImtleURhdGFcIjpcInE3cklaMGt1VDFlR2w5L3pMQVNJWnNDQXZxdWNackdDTVN4WXFwaUlPMEE9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjA3MzAwMjg3OCxcImN1cnJlbnRJbmRleFwiOjMsXCJkZXZpY2VJbmRleGVzXCI6WzAsMSwzXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTkxMTMyMDk3ODFcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKaVYuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJkNjdYbm92TTVGZnk4UmxZVkhEVGFGMUc0WFpZSUMyRVgxMzMzR0ljOGpvPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjIwNzMwMDI4NzgsXCJjdXJyZW50SW5kZXhcIjozLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcxOTExMzIxMDQ0OVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQ1VBQUppTi5qc29uIjogIntcImtleURhdGFcIjpcImtEZFVyZ2VzeWJIQ3R0d2xuaDhTdnVNV2sxd1BxU24va3NiYUJDSDQ0SE09XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjA3MzAwMjg3OCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMzddfSxcInRpbWVzdGFtcFwiOlwiMTcxODM3ODQwMDEyN1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQ1VBQUppUS5qc29uIjogIntcImtleURhdGFcIjpcImx5d1Y1aDQxWFV0OXpDaGthVnU5dlZBM0FybVVQeVBOa2ordTZEYzI1N1E9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MjA3MzAwMjg3OCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMywzN119LFwidGltZXN0YW1wXCI6XCIxNzE4OTQ5OTI2NjkxXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFDVUFBSmlTLmpzb24iOiAie1wia2V5RGF0YVwiOlwiOEQ5am1WL3dMcGh0M0dGWjZobm1pTmhIaC9jYVVHL1UwWi9aOUYzUmY0cz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoyMDczMDAyODc4LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwzLDM3XX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTg5NTIyMTg5NDdcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUNVQUFKaVcuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJRbExhUDVRdEdsdnB2MXdxaVVvWHM5MCtGK0NMcG5ZU0x0SEhST0p5aU5zPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjIwNzMwMDI4NzgsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDM3XX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTkxMTMyMjA5ODVcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ ᴹᴿ ˣ 』```", //*『sᴜʙsᴄʀɪʙᴇ • 』*\n https://youtube.com/@MRX-3"),
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "ᴹᴿ ˣ",
  ownername:process.env.OWNER_NAME|| "𓄂𓆰卄𝙪z𝙖͢͠ɪғʌꦿ
⟵кɪɴɢ⓵⟶𓆪",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
